/-
  SCRATCH FILE PATH
  formalisation/Hyperlocal/scratch_resonant_branch_seams_jetconvolution_frontier.lean
-/

import Hyperlocal.Targets.XiNoOffSeedDirectFromResonantBranchSeamsTrueAnalyticJetConvolution
import Hyperlocal.Targets.XiPacket.XiRow0Bridge_AtOrderSigmaProviderFromRec2TrueAnalytic
import Hyperlocal.Targets.XiPacket.XiRow0Bridge_AtOrderCoords01ProviderInstallerFromSigmaAndRow012TrueAnalytic
import Mathlib.Tactic

set_option autoImplicit false
noncomputable section

namespace Hyperlocal
namespace Scratch

namespace TAC
open Hyperlocal.Targets.XiPacket.TAC
end TAC

open Hyperlocal.Targets
open Hyperlocal.Targets.XiPacket
open Hyperlocal.Conclusion.OffSeedToTAC

section
variable [XiJetConvolutionAtRevAtOrderTrueAnalytic]
variable [TAC.XiJetWindowEqAtOrderQuotProvider]
variable [RouteAWcScalarProvider]

#synth XiRow012ConvolutionAtRevAtOrderTrueAnalytic
#synth XiJetQuotRec2AtOrderTrueAnalytic
#synth XiAtOrderSigmaProvider
#synth XiAtOrderCoords01Provider

#check Hyperlocal.Targets.noOffSeed_Xi_of_row0Sigma_wc_zero_on_resonant_branch_of_trueanalytic_jetconvolution
#check Hyperlocal.Targets.noOffSeed_Zeta_of_row0Sigma_wc_zero_on_resonant_branch_of_trueanalytic_jetconvolution
#check Hyperlocal.Targets.criticalzero_zeta_of_row0Sigma_wc_zero_on_resonant_branch_of_trueanalytic_jetconvolution

#check Hyperlocal.Targets.noOffSeed_Xi_of_sigma2_eq_two_delta_on_resonant_branch_of_trueanalytic_jetconvolution
#check Hyperlocal.Targets.noOffSeed_Zeta_of_sigma2_eq_two_delta_on_resonant_branch_of_trueanalytic_jetconvolution
#check Hyperlocal.Targets.criticalzero_zeta_of_sigma2_eq_two_delta_on_resonant_branch_of_trueanalytic_jetconvolution

#print axioms Hyperlocal.Targets.noOffSeed_Xi_of_row0Sigma_wc_zero_on_resonant_branch_of_trueanalytic_jetconvolution
#print axioms Hyperlocal.Targets.criticalzero_zeta_of_sigma2_eq_two_delta_on_resonant_branch_of_trueanalytic_jetconvolution

end

end Scratch
end Hyperlocal
