import Hyperlocal.Targets.XiNoOffSeedDirectFromFinalLocalScalarTargetTrueAnalyticJetConvolution
import Hyperlocal.Targets.XiPacket.XiRow0Bridge_AtOrderSigmaProviderFromRec2TrueAnalytic
import Hyperlocal.Targets.XiPacket.XiRow0Bridge_AtOrderCoords01ProviderInstallerFromSigmaAndRow012TrueAnalytic
import Mathlib.Tactic

set_option autoImplicit false
noncomputable section

namespace Hyperlocal
namespace Scratch

namespace TAC
open Hyperlocal.Targets.XiPacket.TAC
end TAC

open Hyperlocal.Targets
open Hyperlocal.Targets.XiPacket
open Hyperlocal.Conclusion.OffSeedToTAC

variable
  [XiJetConvolutionAtRevAtOrderTrueAnalytic]
  [TAC.XiJetWindowEqAtOrderQuotProvider]

#synth XiRow012ConvolutionAtRevAtOrderTrueAnalytic
#synth XiJetQuotRec2AtOrderTrueAnalytic
#synth XiAtOrderSigmaProvider
#synth XiAtOrderCoords01Provider

#check Hyperlocal.Targets.noOffSeed_Xi_of_final_local_scalar_target_of_trueanalytic_jetconvolution
#check Hyperlocal.Targets.noOffSeed_Zeta_of_final_local_scalar_target_of_trueanalytic_jetconvolution
#check Hyperlocal.Targets.criticalzero_zeta_of_final_local_scalar_target_of_trueanalytic_jetconvolution

#print axioms Hyperlocal.Targets.noOffSeed_Xi_of_final_local_scalar_target_of_trueanalytic_jetconvolution
#print axioms Hyperlocal.Targets.criticalzero_zeta_of_final_local_scalar_target_of_trueanalytic_jetconvolution

end Scratch
end Hyperlocal
