import Hyperlocal.Targets.CriticalZero_Zeta_FinalFromResonantSigma2Delta
import Mathlib.Tactic

set_option autoImplicit false
noncomputable section

namespace Hyperlocal
namespace Scratch

namespace TAC
open Hyperlocal.Targets.XiPacket.TAC
end TAC

open Hyperlocal.Targets
open Hyperlocal.Targets.XiPacket
open Hyperlocal.Conclusion.OffSeedToTAC

#check Hyperlocal.Targets.noOffSeed_Xi_final_from_resonant_sigma2_eq_two_delta
#check Hyperlocal.Targets.noOffSeed_Zeta_final_from_resonant_sigma2_eq_two_delta
#check Hyperlocal.Targets.criticalzero_zeta_final_from_resonant_sigma2_eq_two_delta

#print axioms Hyperlocal.Targets.noOffSeed_Xi_final_from_resonant_sigma2_eq_two_delta
#print axioms Hyperlocal.Targets.criticalzero_zeta_final_from_resonant_sigma2_eq_two_delta

end Scratch
end Hyperlocal
